[project]
name = "text-to-speech"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    # "torch",
    "transformers",
    "kokoro>=0.3.1",
    "soundfile",
    "misaki[en]"
]

[tool.uv.workspace]
members = [
    "app",
]